repos:
-  repo: local
   hooks:
   - id: requirements
     name: Generate and Add Requirements
     entry: python gerarRequirements.py
     language: system
     pass_filenames: false
     stages: [pre-commit]